[bastion]
bastion ansible_host=158.160.34.89

[web]
web-1 ansible_host=10.10.11.10
web-2 ansible_host=10.10.12.10

[zabbix]
zabbix ansible_host=10.10.1.20

[elasticsearch]
elasticsearch ansible_host=10.10.11.20

[kibana]
kibana ansible_host=10.10.1.30

[private:children]
web
zabbix
elasticsearch
kibana

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_private_key_file=/home/ivan/.ssh/diplom_ed25519

[private:vars]
ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/ivan/.ssh/diplom_ed25519 -o IdentitiesOnly=yes -W %h:%p ubuntu@158.160.34.89"'
